apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        command: ["/usr/local/bin/jenkins.sh"]
        securityContext:
          runAsUser: 1000
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: jenkins
